<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-24T17:20:37 BRT" name="Default suite" finished-at="2020-09-24T17:20:52 BRT" duration-ms="14808">
    <groups>
    </groups>
    <test started-at="2020-09-24T17:20:37 BRT" name="Default test" finished-at="2020-09-24T17:20:52 BRT" duration-ms="14808">
      <class name="homepage.HomePageTests2">
        <test-method is-config="true" signature="inicializar()[pri:0, instance:homepage.HomePageTests2@69e1dd28]" started-at="2020-09-24T17:20:37 BRT" name="inicializar" finished-at="2020-09-24T17:20:41 BRT" duration-ms="3773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicializar -->
        <test-method is-config="true" signature="carregarPaginaInicial()[pri:0, instance:homepage.HomePageTests2@69e1dd28]" started-at="2020-09-24T17:20:41 BRT" name="carregarPaginaInicial" finished-at="2020-09-24T17:20:47 BRT" duration-ms="5916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- carregarPaginaInicial -->
        <test-method signature="testLoginComSucesso_UsuarioLogado()[pri:0, instance:homepage.HomePageTests2@69e1dd28]" started-at="2020-09-24T17:20:47 BRT" name="testLoginComSucesso_UsuarioLogado" finished-at="2020-09-24T17:20:51 BRT" duration-ms="4187" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: is <false>
     but: was <true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: is <false>
     but: was <true>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at homepage.HomePageTests2.testLoginComSucesso_UsuarioLogado(HomePageTests2.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginComSucesso_UsuarioLogado -->
        <test-method is-config="true" signature="preencherRelatorio(org.testng.ITestResult)[pri:0, instance:homepage.HomePageTests2@69e1dd28]" started-at="2020-09-24T17:20:51 BRT" name="preencherRelatorio" finished-at="2020-09-24T17:20:51 BRT" duration-ms="15" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLoginComSucesso_UsuarioLogado status=FAILURE method=HomePageTests2.testLoginComSucesso_UsuarioLogado()[pri:0, instance:homepage.HomePageTests2@69e1dd28] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preencherRelatorio -->
        <test-method is-config="true" signature="finalizar()[pri:0, instance:homepage.HomePageTests2@69e1dd28]" started-at="2020-09-24T17:20:51 BRT" name="finalizar" finished-at="2020-09-24T17:20:52 BRT" duration-ms="871" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalizar -->
      </class> <!-- homepage.HomePageTests2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
